version: "3.9"
services:
  mongo:
    container_name: MongoDB
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - default

  backend:
    build: .
    container_name: Backend
    ports:
      - 6000:6000
    environment:
      - MONGO_URL=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - default
